// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class isread_added_to_messages_and_contacts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(isread_added_to_messages_and_contacts));
        
        string IMigrationMetadata.Id
        {
            get { return "202305211212389_isread_added_to_messages_and_contacts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
